// configure state defaults for the calculator page.
export const DEFAULT_CURRENT_AGE = 30,
DEFAULT_RETIREMENT_AGE = 65,
DEFAULT_LIFE_EXPECTANCY = 95,
DEFAULT_DESIRED_INCOME = 45000,
DEFAULT_DESIRED_ESTATE = 0,

AVERAGE_INFLATION_RATE = 2.2,
AGGRESSIVE_RATE_OF_RETURN = 8,
MODERATE_RATE_OF_RETURN = 6.5,
CONSERVATIVE_RATE_OF_RETURN = 4,

DEFAULT_SAVINGS = 0,
DEFAULT_CONTRIBUTIONS = 0,
DEFAULT_CONTRIBUTION_INCREASE = 2,


DEFAULT_PENSION_START = 65,
DEFAULT_COST_OF_LIVING_ADJUSTMENT = 2,
DEFAULT_MONTHLY_INCOME = 0
